### ISSUE TITLE
OpenDBC

### ISSUE THREAD

**Issue by brainstorm** [projectgus/mitsubishi-outlander-phev-can-logs#1]
Yet another Yak to look at (not necessarily shave), if you were not aware of it: https://github.com/commaai/opendbc

... I thought it might help out classifying and decoding all your CAN messages (specially [cabana](https://github.com/commaai/cabana), haven't used it yet, but looks quite well suited for your current efforts) :)

**Comment by projectgus** [comment]
Thanks @brainstorm :)

The cabana tool does look really nice. I've been using SavvyCAN so far, but will check cabana out.
